---
subdomain_name: meet
host_ip: 104.64.205.66
jitsi_cfg_dir: '{{ home_dir }}/.jitsi-meet-cfg'
jitsi_dir: '{{ home_dir }}/jitsi'
jitsi_docker_dir: '{{ jitsi_dir }}/jitsi-docker-jitsi-meet-3de7148'
jitsi_jigasi_dir: '{{ jitsi_dir }}/jigasi-0ab957c'
jitsi_jigasi_deb_path: '{{ jitsi_dir }}/jigasi_1.1-12-g76f5e50-1_all.deb'
jitsi_web_dir: '{{ jitsi_dir }}/jitsi-meet-stable-jitsi-meet_9457'
jitsi_web_config_deb_path: '{{ jitsi_dir }}/jitsi-meet-web-config_1.0.2-1_all.deb'
jitsi_web_deb_path: '{{ jitsi_dir }}/jitsi-meet-web_1.0.2-1_all.deb'
