---
argument_specs:
  main:
    options:
      chdir:
        type: str
        required: true
        description: >
          Absolute path to the project directory on the target host.

      target_service:
        type: str
        required: true
        choices:
          - ai-scribe
          - backend
          - care-assistant
          - caremate-agent
          - caremate-chain
          - caremate-mcp
          - cengine-api
          - doc-cat-api
          - mental-care
          - nginx
          - pacs-server
          - postgres
          - redis
          - server
        description: >
          Name of the Docker service to restart.
