---
argument_specs:
  main:
    options:
      chdir:
        type: str
        required: true
        description: >
          Absolute path to the project directory on the target host.

      target_service:
        type: str
        required: true
        description: >
          Name of the Docker service to restart.
