---
- name: Deploy caremate-chain
  hosts: chain-server
  roles:
    - role: git-puller
      repo: 'git@github.com:nguyen2v/{{ project_name }}.git'
      dest: '{{ project_name }}'

    - role: docker-compose-helper
      chdir: '{{ project_dir }}'
      target_service: caremate-chain
