---
- name: Deploy caremate-chain
  hosts: all
  vars:
    service_name: sepsis
    target_sub_project: '{{ sub_project | default(service_name) }}'
  roles:
    - role: git-puller
      repo: 'git@github.com:nguyen2v/{{ project_name }}.git'
      dest: '{{ project_name }}'

    - role: docker-compose-helper
      chdir: '{{ project_dir }}'
      target_service: '{{ target_sub_project }}'
