---
- name: Setup nginx (https certificate)
  hosts: all
  vars:
    ssl: true
    server: caremate
  roles:
    - role: nginx-docker-helper
      enable_ssl: '{{ ssl }}'
      server_name: '{{ server }}'

    - role: certbot-helper
      when: not ssl
